# Stage builder
FROM golang:1.24 AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o gateway ./main.go

# Stage runtime
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/gateway .
RUN chmod +x ./gateway
EXPOSE 8080
CMD ["./gateway"]
