# Stage builder
FROM golang:1.25 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o task-service ./main.go

# Stage runtime
FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/task-service .
RUN chmod +x ./task-service
EXPOSE 50052
CMD ["./task-service"]
