// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: protoc/report.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request cho báo cáo
type ReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Có thể lọc theo user hoặc project (tùy nhu cầu)
	UserId        int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     int32 `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_protoc_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_protoc_report_proto_rawDescGZIP(), []int{0}
}

func (x *ReportRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReportRequest) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

// Response thống kê task
type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *TaskStats             `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_protoc_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_protoc_report_proto_rawDescGZIP(), []int{1}
}

func (x *ReportResponse) GetStats() *TaskStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// Thông tin chi tiết thống kê task
type TaskStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalTasks       int32                  `protobuf:"varint,1,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`                                                                                                // Tổng số task
	CompletedTasks   int32                  `protobuf:"varint,2,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`                                                                                    // Số task đã hoàn thành
	PendingTasks     int32                  `protobuf:"varint,3,opt,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`                                                                                          // Số task chưa hoàn thành
	TasksPerProject  map[int32]int32        `protobuf:"bytes,4,rep,name=tasks_per_project,json=tasksPerProject,proto3" json:"tasks_per_project,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`    // project_id -> số lượng task
	TasksPerPriority map[int32]int32        `protobuf:"bytes,5,rep,name=tasks_per_priority,json=tasksPerPriority,proto3" json:"tasks_per_priority,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // priority -> số lượng task
	TasksPerUser     map[int32]int32        `protobuf:"bytes,6,rep,name=tasks_per_user,json=tasksPerUser,proto3" json:"tasks_per_user,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`             // user_id -> số lượng task
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskStats) Reset() {
	*x = TaskStats{}
	mi := &file_protoc_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStats) ProtoMessage() {}

func (x *TaskStats) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStats.ProtoReflect.Descriptor instead.
func (*TaskStats) Descriptor() ([]byte, []int) {
	return file_protoc_report_proto_rawDescGZIP(), []int{2}
}

func (x *TaskStats) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *TaskStats) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *TaskStats) GetPendingTasks() int32 {
	if x != nil {
		return x.PendingTasks
	}
	return 0
}

func (x *TaskStats) GetTasksPerProject() map[int32]int32 {
	if x != nil {
		return x.TasksPerProject
	}
	return nil
}

func (x *TaskStats) GetTasksPerPriority() map[int32]int32 {
	if x != nil {
		return x.TasksPerPriority
	}
	return nil
}

func (x *TaskStats) GetTasksPerUser() map[int32]int32 {
	if x != nil {
		return x.TasksPerUser
	}
	return nil
}

var File_protoc_report_proto protoreflect.FileDescriptor

const file_protoc_report_proto_rawDesc = "" +
	"\n" +
	"\x13protoc/report.proto\x12\x06report\"G\n" +
	"\rReportRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x05R\tprojectId\"9\n" +
	"\x0eReportResponse\x12'\n" +
	"\x05stats\x18\x01 \x01(\v2\x11.report.TaskStatsR\x05stats\"\xba\x04\n" +
	"\tTaskStats\x12\x1f\n" +
	"\vtotal_tasks\x18\x01 \x01(\x05R\n" +
	"totalTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x02 \x01(\x05R\x0ecompletedTasks\x12#\n" +
	"\rpending_tasks\x18\x03 \x01(\x05R\fpendingTasks\x12R\n" +
	"\x11tasks_per_project\x18\x04 \x03(\v2&.report.TaskStats.TasksPerProjectEntryR\x0ftasksPerProject\x12U\n" +
	"\x12tasks_per_priority\x18\x05 \x03(\v2'.report.TaskStats.TasksPerPriorityEntryR\x10tasksPerPriority\x12I\n" +
	"\x0etasks_per_user\x18\x06 \x03(\v2#.report.TaskStats.TasksPerUserEntryR\ftasksPerUser\x1aB\n" +
	"\x14TasksPerProjectEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aC\n" +
	"\x15TasksPerPriorityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a?\n" +
	"\x11TasksPerUserEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012O\n" +
	"\rReportService\x12>\n" +
	"\rGetTaskReport\x12\x15.report.ReportRequest\x1a\x16.report.ReportResponseB0Z.taskmanager/microservices/report-service/pb;pbb\x06proto3"

var (
	file_protoc_report_proto_rawDescOnce sync.Once
	file_protoc_report_proto_rawDescData []byte
)

func file_protoc_report_proto_rawDescGZIP() []byte {
	file_protoc_report_proto_rawDescOnce.Do(func() {
		file_protoc_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoc_report_proto_rawDesc), len(file_protoc_report_proto_rawDesc)))
	})
	return file_protoc_report_proto_rawDescData
}

var file_protoc_report_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protoc_report_proto_goTypes = []any{
	(*ReportRequest)(nil),  // 0: report.ReportRequest
	(*ReportResponse)(nil), // 1: report.ReportResponse
	(*TaskStats)(nil),      // 2: report.TaskStats
	nil,                    // 3: report.TaskStats.TasksPerProjectEntry
	nil,                    // 4: report.TaskStats.TasksPerPriorityEntry
	nil,                    // 5: report.TaskStats.TasksPerUserEntry
}
var file_protoc_report_proto_depIdxs = []int32{
	2, // 0: report.ReportResponse.stats:type_name -> report.TaskStats
	3, // 1: report.TaskStats.tasks_per_project:type_name -> report.TaskStats.TasksPerProjectEntry
	4, // 2: report.TaskStats.tasks_per_priority:type_name -> report.TaskStats.TasksPerPriorityEntry
	5, // 3: report.TaskStats.tasks_per_user:type_name -> report.TaskStats.TasksPerUserEntry
	0, // 4: report.ReportService.GetTaskReport:input_type -> report.ReportRequest
	1, // 5: report.ReportService.GetTaskReport:output_type -> report.ReportResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protoc_report_proto_init() }
func file_protoc_report_proto_init() {
	if File_protoc_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_report_proto_rawDesc), len(file_protoc_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_report_proto_goTypes,
		DependencyIndexes: file_protoc_report_proto_depIdxs,
		MessageInfos:      file_protoc_report_proto_msgTypes,
	}.Build()
	File_protoc_report_proto = out.File
	file_protoc_report_proto_goTypes = nil
	file_protoc_report_proto_depIdxs = nil
}
