// Code generated by ent, DO NOT EDIT.

package ent

import (
	"taskmanager/ent/schema"
	"taskmanager/ent/task"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescDone is the schema descriptor for done field.
	taskDescDone := taskFields[1].Descriptor()
	// task.DefaultDone holds the default value on creation for the done field.
	task.DefaultDone = taskDescDone.Default.(bool)
}
