# Stage builder
FROM golang:1.25 AS builder
WORKDIR /app
COPY . .
COPY ../internal/commonrepo ../internal/commonrepo
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o project-service ./main.go

# Stage runtime
FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/project-service .
RUN chmod +x ./project-service
EXPOSE 50053
CMD ["./project-service"]
