# Stage builder
FROM golang:1.25 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
# Copy code của service và cả internal/commonrepo
COPY . .
COPY ../internal/commonrepo ../internal/commonrepo
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o user-service ./main.go

# Stage runtime
FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/user-service .
RUN chmod +x ./user-service
EXPOSE 50051
CMD ["./user-service"]
