# Stage builder
FROM golang:1.24 AS builder
WORKDIR /app
COPY . .
COPY ../internal/commonrepo ../internal/commonrepo
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o user-service ./main.go

# Stage runtime
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/user-service .
RUN chmod +x ./user-service
EXPOSE 50051
CMD ["./user-service"]
