name: Go CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [project-service, task-service, user-service]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y gcc
      - name: Run tests for ${{ matrix.service }}
        working-directory: ./microservices/${{ matrix.service }}
        run: go test -v -tags sqlite3 ./...
      - name: Build Docker image for ${{ matrix.service }}
        working-directory: ./microservices/${{ matrix.service }}
        run: docker build -t ${{ matrix.service }}:latest .
      # Uncomment below to push to Docker Hub
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Push Docker image
      #   run: docker tag ${{ matrix.service }}:latest yourrepo/${{ matrix.service }}:latest && docker push yourrepo/${{ matrix.service }}:latest

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/your/app
            docker-compose pull
            docker-compose up -d
